name: CI

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - '**.md'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.9-jammy
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        # Provide the password for postgres
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_PASSWORD: vapor_password
          POSTGRES_DB: vapor_database
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container: ${{ matrix.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
         DEBIAN_FRONTEND: "noninteractive"
         DEBCONF_NONINTERACTIVE_SEEN: true
        run: |
          apt-get -q update \
          && apt-get -q dist-upgrade -y \
          && apt-get -q install -y \
          ca-certificates \
          tzdata \
          libcurl4 \
          libxml2 \
          && rm -r /var/lib/apt/lists/*

      - name: Run migrations
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_PASSWORD: vapor_password
          POSTGRES_DB: vapor_database
        run: swift run App migrate

      - name: Run Tests
        run: swift test --sanitize=thread
