name: CI

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - '**.md'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.9-jammy
    container: ${{ matrix.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
         DEBIAN_FRONTEND: "noninteractive"
         DEBCONF_NONINTERACTIVE_SEEN: true
        run: |
          apt-get -q update \
          && apt-get -q dist-upgrade -y \
          && apt-get -q install -y \
          ca-certificates \
          tzdata \
          libcurl4 \
          libxml2 \
          && rm -r /var/lib/apt/lists/*

      - name: Run Tests and generate test coverage data
        run: swift test --sanitize=thread
